In [1]:
import pandas as pd
import os
from collections import defaultdict
import re
from tqdm import tqdm
import numpy as np

In [3]:
BASE_DIR = f"/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/Train"

## ChromBPNet

In [4]:
overlap_dict = defaultdict(dict)

cell_types = ['microglia', 'astrocyte', 'neuron', 'oligodendrocyte']

running_total = 0
running_overlap_total = 0

for chrom in range(1,23):
    annotation_dir = os.path.join(BASE_DIR, "annotations", f"chr{chrom}")
    
    for cell in cell_types:
        chrombp=pd.read_csv(f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/58K_preview_compact/rare_variants/chrombpnet/variant_peak_pairs_scored/rare_variant_chrombpnet_{cell}_chr{chrom}_variant_peak_pairs_scored.csv", 
                            sep = "\t")
        print(chrombp.columns)
        print(chrombp.head)
        print(len(chrombp['BP']), len(set(chrombp['BP'].to_list())))
        break

        for file in sorted(os.listdir(annotation_dir)):
            if not file.endswith("_annotations.tsv.gz"):
                continue

            gene = re.sub(r"_annotations\.tsv\.gz$", "", file)
            anno_df = pd.read_csv(os.path.join(annotation_dir, file), sep="\t", usecols=['pos'])

            n_total = len(set(anno_df['pos'].to_list()))
            n_overlap = len((set(chrombp['BP'].to_list())) & (set(anno_df['pos'].to_list())))

            running_total += n_total
            running_overlap_total += n_overlap

            overlap_dict[chrom][gene] = dict()
            overlap_dict[chrom][gene][cell] = (n_total, n_overlap)
    break

Index(['Chr', 'PeakID', 'peak_center', 'SNP', 'CM', 'BP', 'ALT', 'REF',
       'distance_from_center', 'annotationSimple', 'assay',
       'log_counts_diff_chrombpnet', 'log_probs_diff_abs_sum_chrombpnet',
       'probs_jsd_diff_chrombpnet'],
      dtype='object')
<bound method NDFrame.head of          Chr                       PeakID  peak_center              SNP   CM  \
0          1                     Peak_258      3796547    1:3795538:C:G  0.0
1          1                     Peak_258      3796547    1:3795550:T:C  0.0
2          1                     Peak_258      3796547    1:3795575:A:T  0.0
3          1                     Peak_258      3796547    1:3795589:G:A  0.0
4          1                     Peak_258      3796547    1:3795615:A:G  0.0
...      ...                          ...          ...              ...  ...
1800514    1  microglia_H3K4me3_peak_4139    248906494  1:248907470:A:G  0.0
1800515    1  microglia_H3K4me3_peak_4139    248906494  1:248907471:G:A  0.0
1800516    1  microglia_H3K4me3_peak_4139    248906494  1:248907474:C:G  0.0
1800517    1  microglia_H3K4me3_peak_4139    248906494  1:248907491:G:A  0.0
1800518    1  microglia_H3K4me3_peak_4139    248906494  1:248907516:C:T  0.0

                BP ALT REF  distance_from_center annotationSimple    assay  \
0          3795538   G   C                 -1009         Promoter     ATAC
1          3795550   C   T                  -997         Promoter     ATAC
2          3795575   T   A                  -972         Promoter     ATAC
3          3795589   A   G                  -958         Promoter     ATAC
4          3795615   G   A                  -932         Promoter     ATAC
...            ...  ..  ..                   ...              ...      ...
1800514  248907470   G   A                   976          H3K4me3  H3K4me3
1800515  248907471   A   G                   977          H3K4me3  H3K4me3
1800516  248907474   G   C                   980          H3K4me3  H3K4me3
1800517  248907491   A   G                   997          H3K4me3  H3K4me3
1800518  248907516   T   C                  1022          H3K4me3  H3K4me3

         log_counts_diff_chrombpnet  log_probs_diff_abs_sum_chrombpnet  \
0                         -0.000229                          -0.021977
1                         -0.000171                          -0.022922
2                         -0.000273                          -0.038347
3                         -0.000457                          -0.035910
4                          0.000132                           0.014500
...                             ...                                ...
1800514                    0.000115                           0.466617
1800515                   -0.000051                          -0.245380
1800516                    0.000007                           0.084564
1800517                    0.000044                           0.192405
1800518                   -0.000008                          -0.006685

         probs_jsd_diff_chrombpnet
0                              NaN
1                              NaN
2                        -0.000024
3                              NaN
4                         0.000020
...                            ...
1800514                   0.000398
1800515                  -0.000218
1800516                   0.000054
1800517                   0.000194
1800518                        NaN

[1800519 rows x 14 columns]>
1800519 882219

In [24]:
overlap_dict

defaultdict(dict,
            {1: {'ENSG00000000457': {'astrocyte': (5874, 205)},
              'ENSG00000000460': {'astrocyte': (10027, 340)},
              'ENSG00000000938': {'astrocyte': (5674, 488)},
              'ENSG00000000971': {'astrocyte': (6236, 59)},
              'ENSG00000001460': {'astrocyte': (6579, 351)},
              'ENSG00000001461': {'astrocyte': (6463, 354)},
              'ENSG00000004455': {'astrocyte': (6574, 434)},
              'ENSG00000004487': {'astrocyte': (6126, 357)},
              'ENSG00000006555': {'astrocyte': (6172, 266)},
              'ENSG00000007341': {'astrocyte': (7139, 682)},
              'ENSG00000007908': {'astrocyte': (6380, 180)},
              'ENSG00000007923': {'astrocyte': (7433, 885)},
              'ENSG00000007933': {'astrocyte': (5843, 166)},
              'ENSG00000007968': {'astrocyte': (5852, 474)},
              'ENSG00000008118': {'astrocyte': (6161, 473)},
              'ENSG00000008128': {'astrocyte': (6112, 0)},
              'ENSG00000008130': {'astrocyte': (6098, 0)},
              'ENSG00000009307': {'astrocyte': (5852, 266)},
              'ENSG00000009709': {'astrocyte': (9846, 9)},
              'ENSG00000009724': {'astrocyte': (6394, 389)},
              'ENSG00000009780': {'astrocyte': (5745, 263)},
              'ENSG00000009790': {'astrocyte': (5334, 372)},
              'ENSG00000010072': {'astrocyte': (5585, 396)},
              'ENSG00000010165': {'astrocyte': (5646, 327)},
              'ENSG00000010803': {'astrocyte': (10052, 306)},
              'ENSG00000010932': {'astrocyte': (6177, 176)},
              'ENSG00000011007': {'astrocyte': (5365, 426)},
              'ENSG00000011009': {'astrocyte': (5044, 477)},
              'ENSG00000011021': {'astrocyte': (7492, 944)},
              'ENSG00000014914': {'astrocyte': (3876, 556)},
              'ENSG00000016490': {'astrocyte': (5528, 278)},
              'ENSG00000016602': {'astrocyte': (5695, 188)},
              'ENSG00000018625': {'astrocyte': (5873, 1406)},
              'ENSG00000020129': {'astrocyte': (4879, 192)},
              'ENSG00000020633': {'astrocyte': (7324, 34)},
              'ENSG00000021852': {'astrocyte': (6546, 64)},
              'ENSG00000023572': {'astrocyte': (4654, 329)},
              'ENSG00000023902': {'astrocyte': (5045, 421)},
              'ENSG00000023909': {'astrocyte': (5651, 227)},
              'ENSG00000024526': {'astrocyte': (5501, 162)},
              'ENSG00000025800': {'astrocyte': (6451, 649)},
              'ENSG00000026751': {'astrocyte': (5886, 67)},
              'ENSG00000027644': {'astrocyte': (5841, 696)},
              'ENSG00000027869': {'astrocyte': (5688, 779)},
              'ENSG00000028137': {'astrocyte': (6562, 275)},
              'ENSG00000031698': {'astrocyte': (5951, 856)},
              'ENSG00000033122': {'astrocyte': (18622, 274)},
              'ENSG00000034971': {'astrocyte': (5356, 243)},
              'ENSG00000035687': {'astrocyte': (6483, 185)},
              'ENSG00000036549': {'astrocyte': (7533, 273)},
              'ENSG00000037637': {'astrocyte': (7926, 589)},
              'ENSG00000040487': {'astrocyte': (6449, 672)},
              'ENSG00000041988': {'astrocyte': (6008, 827)},
              'ENSG00000042781': {'astrocyte': (26277, 326)},
              'ENSG00000043514': {'astrocyte': (6181, 355)},
              'ENSG00000044012': {'astrocyte': (4977, 50)},
              'ENSG00000047410': {'astrocyte': (6423, 243)},
              'ENSG00000048707': {'astrocyte': (12425, 541)},
              'ENSG00000049089': {'astrocyte': (5175, 325)},
              'ENSG00000049239': {'astrocyte': (7289, 538)},
              'ENSG00000049245': {'astrocyte': (5714, 275)},
              'ENSG00000049246': {'astrocyte': (6972, 287)},
              'ENSG00000049247': {'astrocyte': (5552, 229)},
              'ENSG00000049249': {'astrocyte': (5894, 318)},
              'ENSG00000050628': {'astrocyte': (9803, 155)},
              'ENSG00000052723': {'astrocyte': (5069, 262)},
              'ENSG00000053371': {'astrocyte': (6202, 682)},
              'ENSG00000053372': {'astrocyte': (5874, 628)},
              'ENSG00000054116': {'astrocyte': (5613, 688)},
              'ENSG00000054118': {'astrocyte': (7604, 779)},
              'ENSG00000054267': {'astrocyte': (10185, 395)},
              'ENSG00000054277': {'astrocyte': (7015, 190)},
              'ENSG00000054282': {'astrocyte': (9908, 399)},
              'ENSG00000054392': {'astrocyte': (15127, 421)},
              'ENSG00000054523': {'astrocyte': (9612, 760)},
              'ENSG00000055070': {'astrocyte': (6533, 324)},
              'ENSG00000055732': {'astrocyte': (5381, 212)},
              'ENSG00000057252': {'astrocyte': (6950, 290)},
              'ENSG00000057468': {'astrocyte': (7605, 207)},
              'ENSG00000057757': {'astrocyte': (5188, 477)},
              'ENSG00000058085': {'astrocyte': (6562, 159)},
              'ENSG00000058453': {'astrocyte': (8847, 830)},
              'ENSG00000058668': {'astrocyte': (8354, 397)},
              'ENSG00000058673': {'astrocyte': (6693, 290)},
              'ENSG00000058799': {'astrocyte': (5941, 227)},
              'ENSG00000058804': {'astrocyte': (6909, 219)},
              'ENSG00000059588': {'astrocyte': (7810, 471)},
              'ENSG00000060642': {'astrocyte': (4715, 617)},
              'ENSG00000060656': {'astrocyte': (7435, 290)},
              'ENSG00000060688': {'astrocyte': (6008, 163)},
              'ENSG00000060718': {'astrocyte': (12224, 130)},
              'ENSG00000064703': {'astrocyte': (5389, 379)},
              'ENSG00000064886': {'astrocyte': (6374, 258)},
              'ENSG00000065135': {'astrocyte': (5739, 962)},
              'ENSG00000065183': {'astrocyte': (5541, 147)},
              'ENSG00000065243': {'astrocyte': (8490, 200)},
              'ENSG00000065526': {'astrocyte': (7773, 907)},
              'ENSG00000065600': {'astrocyte': (5836, 365)},
              'ENSG00000065978': {'astrocyte': (5286, 185)},
              'ENSG00000066027': {'astrocyte': (6384, 329)},
              'ENSG00000066056': {'astrocyte': (5508, 371)},
              'ENSG00000066135': {'astrocyte': (6785, 377)},
              'ENSG00000066136': {'astrocyte': (7063, 399)},
              'ENSG00000066185': {'astrocyte': (5602, 276)},
              'ENSG00000066279': {'astrocyte': (6337, 235)},
              'ENSG00000066294': {'astrocyte': (6565, 13)},
              'ENSG00000066322': {'astrocyte': (4994, 594)},
              'ENSG00000066557': {'astrocyte': (5719, 244)},
              'ENSG00000067208': {'astrocyte': (11346, 485)},
              'ENSG00000067334': {'astrocyte': (5300, 231)},
              'ENSG00000067533': {'astrocyte': (6621, 267)},
              'ENSG00000067606': {'astrocyte': (12452, 0)},
              'ENSG00000067704': {'astrocyte': (5874, 209)},
              'ENSG00000069248': {'astrocyte': (7158, 317)},
              'ENSG00000069275': {'astrocyte': (5774, 741)},
              'ENSG00000069424': {'astrocyte': (9949, 361)},
              'ENSG00000069702': {'astrocyte': (10991, 237)},
              'ENSG00000069812': {'astrocyte': (6471, 584)},
              'ENSG00000070759': {'astrocyte': (8217, 744)},
              'ENSG00000070785': {'astrocyte': (7991, 855)},
              'ENSG00000070831': {'astrocyte': (7792, 213)},
              'ENSG00000070886': {'astrocyte': (6804, 37)},
              'ENSG00000072694': {'astrocyte': (4456, 228)},
              'ENSG00000073754': {'astrocyte': (7172, 73)},
              'ENSG00000073756': {'astrocyte': (5498, 88)},
              'ENSG00000074800': {'astrocyte': (6048, 364)},
              'ENSG00000074964': {'astrocyte': (10440, 519)},
              'ENSG00000075151': {'astrocyte': (13755, 383)},
              'ENSG00000075391': {'astrocyte': (14055, 390)},
              'ENSG00000075945': {'astrocyte': (8958, 226)},
              'ENSG00000076258': {'astrocyte': (6134, 102)},
              'ENSG00000076321': {'astrocyte': (5787, 247)},
              'ENSG00000076356': {'astrocyte': (11635, 711)},
              'ENSG00000076864': {'astrocyte': (7413, 496)},
              'ENSG00000077152': {'astrocyte': (4812, 178)},
              'ENSG00000077157': {'astrocyte': (9495, 243)},
              'ENSG00000077254': {'astrocyte': (5961, 250)},
              'ENSG00000077522': {'astrocyte': (8259, 328)},
              'ENSG00000077549': {'astrocyte': (10238, 737)},
              'ENSG00000077585': {'astrocyte': (7827, 450)},
              'ENSG00000078369': {'astrocyte': (8984, 0)},
              'ENSG00000078618': {'astrocyte': (6562, 305)},
              'ENSG00000078808': {'astrocyte': (8767, 0)},
              'ENSG00000078900': {'astrocyte': (9975, 47)},
              'ENSG00000079277': {'astrocyte': (6524, 626)},
              'ENSG00000079335': {'astrocyte': (9051, 408)},
              'ENSG00000079739': {'astrocyte': (6604, 202)},
              'ENSG00000080910': {'astrocyte': (5967, 22)},
              'ENSG00000081019': {'astrocyte': (5199, 360)},
              'ENSG00000081026': {'astrocyte': (10365, 206)},
              'ENSG00000081237': {'astrocyte': (7788, 223)},
              'ENSG00000081248': {'astrocyte': (7791, 1053)},
              'ENSG00000081277': {'astrocyte': (7430, 393)},
              'ENSG00000081692': {'astrocyte': (5207, 177)},
              'ENSG00000081721': {'astrocyte': (4572, 241)},
              'ENSG00000081870': {'astrocyte': (5880, 275)},
              'ENSG00000081985': {'astrocyte': (7207, 200)},
              'ENSG00000082482': {'astrocyte': (10251, 64)},
              'ENSG00000082497': {'astrocyte': (5605, 267)},
              'ENSG00000082512': {'astrocyte': (5785, 271)},
              'ENSG00000083444': {'astrocyte': (7340, 720)},
              'ENSG00000084070': {'astrocyte': (6725, 470)},
              'ENSG00000084072': {'astrocyte': (6889, 379)},
              'ENSG00000084073': {'astrocyte': (5661, 327)},
              'ENSG00000084623': {'astrocyte': (4789, 481)},
              'ENSG00000084628': {'astrocyte': (7170, 100)},
              'ENSG00000084636': {'astrocyte': (6421, 752)},
              'ENSG00000084652': {'astrocyte': (5144, 526)},
              'ENSG00000085433': {'astrocyte': (6625, 710)},
              'ENSG00000085465': {'astrocyte': (5677, 340)},
              'ENSG00000085491': {'astrocyte': (4883, 126)},
              'ENSG00000085552': {'astrocyte': (5654, 585)},
              'ENSG00000085831': {'astrocyte': (6229, 182)},
              'ENSG00000085832': {'astrocyte': (8664, 299)},
              'ENSG00000085840': {'astrocyte': (5332, 286)},
              'ENSG00000085998': {'astrocyte': (5407, 488)},
              'ENSG00000085999': {'astrocyte': (5710, 542)},
              'ENSG00000086015': {'astrocyte': (10731, 300)},
              'ENSG00000086619': {'astrocyte': (7329, 316)},
              'ENSG00000088035': {'astrocyte': (6501, 149)},
              'ENSG00000088280': {'astrocyte': (6604, 665)},
              'ENSG00000090020': {'astrocyte': (6626, 273)},
              'ENSG00000090104': {'astrocyte': (5092, 108)},
              'ENSG00000090273': {'astrocyte': (5808, 529)},
              'ENSG00000090432': {'astrocyte': (5410, 344)},
              'ENSG00000090621': {'astrocyte': (5315, 568)},
              'ENSG00000090686': {'astrocyte': (8536, 468)},
              'ENSG00000091483': {'astrocyte': (5722, 152)},
              'ENSG00000092607': {'astrocyte': (7740, 79)},
              'ENSG00000092621': {'astrocyte': (7871, 559)},
              'ENSG00000092847': {'astrocyte': (6055, 265)},
              'ENSG00000092850': {'astrocyte': (5012, 570)},
              'ENSG00000092853': {'astrocyte': (5698, 338)},
              'ENSG00000092969': {'astrocyte': (7759, 300)},
              'ENSG00000092978': {'astrocyte': (10334, 149)},
              'ENSG00000094963': {'astrocyte': (5705, 199)},
              'ENSG00000094975': {'astrocyte': (6737, 147)},
              'ENSG00000097021': {'astrocyte': (10086, 800)},
              'ENSG00000097033': {'astrocyte': (6033, 149)},
              'ENSG00000097046': {'astrocyte': (5602, 122)},
              'ENSG00000097096': {'astrocyte': (5621, 314)},
              'ENSG00000099260': {'astrocyte': (6348, 141)},
              'ENSG00000107404': {'astrocyte': (8127, 0)},
              'ENSG00000116128': {'astrocyte': (7728, 518)},
              'ENSG00000116132': {'astrocyte': (7140, 313)},
              'ENSG00000116133': {'astrocyte': (6691, 279)},
              'ENSG00000116138': {'astrocyte': (7193, 446)},
              'ENSG00000116141': {'astrocyte': (8133, 279)},
              'ENSG00000116147': {'astrocyte': (17370, 349)},
              'ENSG00000116151': {'astrocyte': (10437, 0)},
              'ENSG00000116157': {'astrocyte': (4932, 303)},
              'ENSG00000116161': {'astrocyte': (5216, 302)},
              'ENSG00000116171': {'astrocyte': (8730, 445)},
              'ENSG00000116183': {'astrocyte': (13238, 169)},
              'ENSG00000116191': {'astrocyte': (9857, 193)},
              'ENSG00000116194': {'astrocyte': (5541, 122)},
              'ENSG00000116198': {'astrocyte': (8373, 202)},
              'ENSG00000116199': {'astrocyte': (6346, 273)},
              'ENSG00000116205': {'astrocyte': (6574, 261)},
              'ENSG00000116209': {'astrocyte': (5749, 275)},
              'ENSG00000116212': {'astrocyte': (5649, 309)},
              'ENSG00000116213': {'astrocyte': (8077, 0)},
              'ENSG00000116218': {'astrocyte': (5630, 79)},
              'ENSG00000116221': {'astrocyte': (6773, 388)},
              'ENSG00000116237': {'astrocyte': (6773, 424)},
              'ENSG00000116251': {'astrocyte': (7116, 420)},
              'ENSG00000116254': {'astrocyte': (8986, 461)},
              'ENSG00000116260': {'astrocyte': (6588, 355)},
              'ENSG00000116266': {'astrocyte': (6260, 584)},
              'ENSG00000116273': {'astrocyte': (5993, 884)},
              'ENSG00000116285': {'astrocyte': (5542, 267)},
              'ENSG00000116288': {'astrocyte': (5818, 267)},
              'ENSG00000116299': {'astrocyte': (7759, 1035)},
              'ENSG00000116329': {'astrocyte': (6278, 214)},
              'ENSG00000116337': {'astrocyte': (4489, 688)},
              'ENSG00000116350': {'astrocyte': (5600, 339)},
              'ENSG00000116353': {'astrocyte': (5903, 367)},
              'ENSG00000116396': {'astrocyte': (6763, 617)},
              'ENSG00000116406': {'astrocyte': (6286, 416)},
              'ENSG00000116455': {'astrocyte': (5443, 352)},
              'ENSG00000116459': {'astrocyte': (5551, 319)},
              'ENSG00000116473': {'astrocyte': (9374, 811)},
              'ENSG00000116478': {'astrocyte': (5605, 709)},
              'ENSG00000116489': {'astrocyte': (5968, 527)},
              'ENSG00000116497': {'astrocyte': (5840, 503)},
              'ENSG00000116514': {'astrocyte': (5555, 499)},
              'ENSG00000116521': {'astrocyte': (4520, 972)},
              'ENSG00000116525': {'astrocyte': (5545, 301)},
              'ENSG00000116539': {'astrocyte': (9820, 720)},
              'ENSG00000116544': {'astrocyte': (6381, 448)},
              'ENSG00000116560': {'astrocyte': (5810, 274)},
              'ENSG00000116574': {'astrocyte': (5227, 116)},
              'ENSG00000116580': {'astrocyte': (6870, 548)},
              'ENSG00000116584': {'astrocyte': (5861, 872)},
              'ENSG00000116586': {'astrocyte': (4674, 787)},
              'ENSG00000116604': {'astrocyte': (5931, 874)},
              'ENSG00000116641': {'astrocyte': (10139, 469)},
              'ENSG00000116649': {'astrocyte': (5844, 379)},
              'ENSG00000116661': {'astrocyte': (6362, 598)},
              'ENSG00000116663': {'astrocyte': (6075, 598)},
              'ENSG00000116667': {'astrocyte': (10632, 412)},
              'ENSG00000116668': {'astrocyte': (7805, 252)},
              'ENSG00000116670': {'astrocyte': (6338, 697)},
              'ENSG00000116675': {'astrocyte': (8600, 375)},
              'ENSG00000116678': {'astrocyte': (9723, 198)},
              'ENSG00000116679': {'astrocyte': (5241, 176)},
              'ENSG00000116685': {'astrocyte': (6357, 680)},
              'ENSG00000116688': {'astrocyte': (6996, 716)},
              'ENSG00000116690': {'astrocyte': (5466, 197)},
              'ENSG00000116691': {'astrocyte': (6111, 523)},
              'ENSG00000116698': {'astrocyte': (7824, 559)},
              'ENSG00000116701': {'astrocyte': (5629, 498)},
              'ENSG00000116703': {'astrocyte': (5094, 124)},
              'ENSG00000116704': {'astrocyte': (6108, 401)},
              'ENSG00000116711': {'astrocyte': (9044, 124)},
              'ENSG00000116717': {'astrocyte': (5352, 153)},
              'ENSG00000116721': {'astrocyte': (7034, 7)},
              'ENSG00000116726': {'astrocyte': (6926, 7)},
              'ENSG00000116729': {'astrocyte': (8815, 413)},
              'ENSG00000116731': {'astrocyte': (9070, 104)},
              'ENSG00000116741': {'astrocyte': (4715, 69)},
              'ENSG00000116745': {'astrocyte': (5565, 175)},
              'ENSG00000116747': {'astrocyte': (5071, 329)},
              'ENSG00000116748': {'astrocyte': (5262, 304)},
              'ENSG00000116750': {'astrocyte': (5446, 244)},
              'ENSG00000116752': {'astrocyte': (5188, 203)},
              'ENSG00000116754': {'astrocyte': (5432, 250)},
              'ENSG00000116761': {'astrocyte': (5362, 89)},
              'ENSG00000116771': {'astrocyte': (5709, 354)},
              'ENSG00000116774': {'astrocyte': (6621, 602)},
              'ENSG00000116783': {'astrocyte': (12472, 179)},
              'ENSG00000116785': {'astrocyte': (4516, 22)},
              'ENSG00000116786': {'astrocyte': (6920, 618)},
              'ENSG00000116791': {'astrocyte': (5646, 165)},
              'ENSG00000116793': {'astrocyte': (5295, 194)},
              'ENSG00000116809': {'astrocyte': (6332, 945)},
              'ENSG00000116815': {'astrocyte': (5586, 335)},
              'ENSG00000116819': {'astrocyte': (5188, 170)},
              'ENSG00000116824': {'astrocyte': (5832, 143)},
              'ENSG00000116830': {'astrocyte': (6053, 452)},
              'ENSG00000116833': {'astrocyte': (9044, 66)},
              'ENSG00000116852': {'astrocyte': (7094, 935)},
              'ENSG00000116857': {'astrocyte': (7175, 696)},
              'ENSG00000116863': {'astrocyte': (5063, 577)},
              'ENSG00000116871': {'astrocyte': (5849, 689)},
              'ENSG00000116874': {'astrocyte': (7575, 122)},
              'ENSG00000116882': {'astrocyte': (6327, 92)},
              'ENSG00000116885': {'astrocyte': (6410, 423)},
              'ENSG00000116898': {'astrocyte': (5640, 285)},
              'ENSG00000116903': {'astrocyte': (5300, 396)},
              'ENSG00000116906': {'astrocyte': (6215, 352)},
              'ENSG00000116918': {'astrocyte': (5815, 234)},
              'ENSG00000116922': {'astrocyte': (5571, 302)},
              'ENSG00000116954': {'astrocyte': (5748, 261)},
              'ENSG00000116962': {'astrocyte': (8206, 502)},
              'ENSG00000116977': {'astrocyte': (6987, 263)},
              'ENSG00000116981': {'astrocyte': (5386, 402)},
              'ENSG00000116983': {'astrocyte': (5335, 369)},
              'ENSG00000116984': {'astrocyte': (8675, 271)},
              'ENSG00000116985': {'astrocyte': (5889, 286)},
              'ENSG00000116990': {'astrocyte': (5250, 257)},
              'ENSG00000116991': {'astrocyte': (9828, 160)},
              'ENSG00000116996': {'astrocyte': (5860, 103)},
              'ENSG00000117000': {'astrocyte': (6879, 259)},
              'ENSG00000117009': {'astrocyte': (6493, 182)},
              'ENSG00000117010': {'astrocyte': (5413, 215)},
              'ENSG00000117013': {'astrocyte': (6876, 297)},

## Enformer

In [14]:
def scale(df):
    df = np.arcsinh(df)
    return (df-df.min())/ (df.max() - df.min())

overlap_dict = defaultdict(dict)

cell_types = ['microglia', 'astrocyte', 'neuron', 'oligodendrocyte']

running_total = 0
running_overlap_total = 0

for chrom in range(1,23):
    annotation_dir = os.path.join(BASE_DIR, "annotations", f"chr{chrom}")
    
    for cell in cell_types:
        print(cell)
        path = f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/ADSP_rare_variants_enformer_delta_scores_annotations_{cell}.tsv.gz"
        newpath = f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/Alzheimer-RV/data/gene_matrices_maf/enformer_scored_06_03_2025/annotations_scaled/ADSP_rare_variants_06_03_2025_enformer_delta_scores_annotations_{cell}.tsv.gz"
        enformer1 = pd.read_csv(path, 
                            sep = "\t")
        print(enformer1.columns)
        enformer2 = pd.read_csv(newpath,
                            sep = "\t")
        print(enformer2.columns)
        # enformer2 = enformer2.rename(columns={'POS': 'pos', 'REF': 'ref', 'ALT': 'alt'})
        # enformer = pd.concat([enformer1, enformer2])
        # enformer = pd.concat([enformer1, enformer2])
        # print(enformer.columns)
        # print(enformer.head)
        # break
        # enformer = enformer[enformer['CHR']==int(chrom)]

        # for file in sorted(os.listdir(annotation_dir)):
        #     if not file.endswith("_annotations.tsv.gz"):
        #         continue

        #     gene = re.sub(r"_annotations\.tsv\.gz$", "", file)
        #     anno_df = pd.read_csv(os.path.join(annotation_dir, file), sep="\t")

        #     n_total = len(set(anno_df['pos'].astype(float).to_list()))
        #     n_overlap1 = len((set(enformer['BP'].to_list())) & (set(anno_df['pos'].to_list())))
        #     n_overlap2 = len((set(enformer2['POS'].to_list())) & (set(anno_df['pos'].to_list())))

        #     running_total += n_total
        #     running_overlap_total += n_overlap1 

        #     overlap_dict[chrom][gene] = dict()
        #     overlap_dict[chrom][gene][cell] = (n_total, n_overlap1, n_overlap2)
    break

microglia
Index(['CHR', 'SNP', 'BP', 'A1', 'A2', 'monocyte_DNASE_delta',
       'monocyte_H3K27ac_delta', 'monocyte_H3K27me3_delta',
       'monocyte_H3K4me3_delta', 'microglia_TF_delta_max',
       'microglia_TF_delta_min'],
      dtype='object')
Index(['CHR', 'SNP', 'POS', 'REF', 'ALT', 'monocyte_DNASE_delta',
       'monocyte_H3K27ac_delta', 'monocyte_H3K27me3_delta',
       'monocyte_H3K4me3_delta', 'microglia_TF_delta_max',
       'microglia_TF_delta_min'],
      dtype='object')
astrocyte
Index(['CHR', 'SNP', 'BP', 'A1', 'A2', 'astrocyte_TF_delta_max',
       'astrocyte_TF_delta_min'],
      dtype='object')
Index(['CHR', 'SNP', 'POS', 'REF', 'ALT', 'astrocyte_TF_delta_max',
       'astrocyte_TF_delta_min'],
      dtype='object')
neuron
Index(['CHR', 'SNP', 'BP', 'A1', 'A2', 'neuronal_TF_delta_max',
       'neuronal_TF_delta_min'],
      dtype='object')
Index(['CHR', 'SNP', 'POS', 'REF', 'ALT', 'neuronal_TF_delta_max',
       'neuronal_TF_delta_min'],
      dtype='object')
oligodendrocyte
Index(['CHR', 'SNP', 'BP', 'A1', 'A2', 'oligodendrocyte_TF_delta_max',
       'oligodendrocyte_TF_delta_min'],
      dtype='object')
Index(['CHR', 'SNP', 'POS', 'REF', 'ALT', 'oligodendrocyte_TF_delta_max',
       'oligodendrocyte_TF_delta_min'],
      dtype='object')

In [32]:
overlap_dict

defaultdict(dict,
            {1: {'ENSG00000000457': {'microglia': (5874, 100, 341)},
              'ENSG00000000460': {'microglia': (10027, 208, 631)},
              'ENSG00000000938': {'microglia': (5674, 162, 1379)},
              'ENSG00000000971': {'microglia': (6236, 62, 0)},
              'ENSG00000001460': {'microglia': (6579, 141, 1610)},
              'ENSG00000001461': {'microglia': (6463, 134, 1784)},
              'ENSG00000004455': {'microglia': (6574, 155, 2008)},
              'ENSG00000004487': {'microglia': (6126, 82, 1407)},
              'ENSG00000006555': {'microglia': (6172, 212, 1448)},
              'ENSG00000007341': {'microglia': (7139, 256, 1749)},
              'ENSG00000007908': {'microglia': (6380, 115, 499)},
              'ENSG00000007923': {'microglia': (7433, 313, 2588)},
              'ENSG00000007933': {'microglia': (5843, 89, 155)},
              'ENSG00000007968': {'microglia': (5852, 152, 1471)},
              'ENSG00000008118': {'microglia': (6161, 225, 0)},
              'ENSG00000008128': {'microglia': (6112, 243, 2813)},
              'ENSG00000008130': {'microglia': (6098, 137, 2502)},
              'ENSG00000009307': {'microglia': (5852, 141, 828)},
              'ENSG00000009709': {'microglia': (9846, 41, 1580)},
              'ENSG00000009724': {'microglia': (6394, 218, 1741)},
              'ENSG00000009780': {'microglia': (5745, 90, 1266)},
              'ENSG00000009790': {'microglia': (5334, 212, 0)},
              'ENSG00000010072': {'microglia': (5585, 100, 0)},
              'ENSG00000010165': {'microglia': (5646, 108, 175)},
              'ENSG00000010803': {'microglia': (10052, 153, 2108)},
              'ENSG00000010932': {'microglia': (6177, 81, 121)},
              'ENSG00000011007': {'microglia': (5365, 154, 1280)},
              'ENSG00000011009': {'microglia': (5044, 188, 1344)},
              'ENSG00000011021': {'microglia': (7492, 306, 2690)},
              'ENSG00000014914': {'microglia': (3876, 171, 912)},
              'ENSG00000016490': {'microglia': (5528, 133, 1036)},
              'ENSG00000016602': {'microglia': (5695, 87, 890)},
              'ENSG00000018625': {'microglia': (5873, 495, 259)},
              'ENSG00000020129': {'microglia': (4879, 82, 1213)},
              'ENSG00000020633': {'microglia': (7324, 20, 1661)},
              'ENSG00000021852': {'microglia': (6546, 74, 1160)},
              'ENSG00000023572': {'microglia': (4654, 117, 0)},
              'ENSG00000023902': {'microglia': (5045, 132, 878)},
              'ENSG00000023909': {'microglia': (5651, 155, 846)},
              'ENSG00000024526': {'microglia': (5501, 90, 827)},
              'ENSG00000025800': {'microglia': (6451, 234, 1958)},
              'ENSG00000026751': {'microglia': (5886, 129, 111)},
              'ENSG00000027644': {'microglia': (5841, 361, 266)},
              'ENSG00000027869': {'microglia': (5688, 381, 192)},
              'ENSG00000028137': {'microglia': (6562, 268, 1586)},
              'ENSG00000031698': {'microglia': (5951, 334, 1695)},
              'ENSG00000033122': {'microglia': (18622, 104, 3237)},
              'ENSG00000034971': {'microglia': (5356, 124, 95)},
              'ENSG00000035687': {'microglia': (6483, 56, 0)},
              'ENSG00000036549': {'microglia': (7533, 118, 1388)},
              'ENSG00000037637': {'microglia': (7926, 218, 1957)},
              'ENSG00000040487': {'microglia': (6449, 151, 1718)},
              'ENSG00000041988': {'microglia': (6008, 296, 2253)},
              'ENSG00000042781': {'microglia': (26277, 312, 0)},
              'ENSG00000043514': {'microglia': (6181, 166, 1832)},
              'ENSG00000044012': {'microglia': (4977, 18, 1305)},
              'ENSG00000047410': {'microglia': (6423, 133, 105)},
              'ENSG00000048707': {'microglia': (12425, 379, 2565)},
              'ENSG00000049089': {'microglia': (5175, 226, 1395)},
              'ENSG00000049239': {'microglia': (7289, 188, 1628)},
              'ENSG00000049245': {'microglia': (5714, 142, 1629)},
              'ENSG00000049246': {'microglia': (6972, 168, 2029)},
              'ENSG00000049247': {'microglia': (5552, 138, 1584)},
              'ENSG00000049249': {'microglia': (5894, 123, 1509)},
              'ENSG00000050628': {'microglia': (9803, 72, 1532)},
              'ENSG00000052723': {'microglia': (5069, 115, 725)},
              'ENSG00000053371': {'microglia': (6202, 169, 1667)},
              'ENSG00000053372': {'microglia': (5874, 216, 1652)},
              'ENSG00000054116': {'microglia': (5613, 234, 1951)},
              'ENSG00000054118': {'microglia': (7604, 318, 2448)},
              'ENSG00000054267': {'microglia': (10185, 122, 0)},
              'ENSG00000054277': {'microglia': (7015, 189, 0)},
              'ENSG00000054282': {'microglia': (9908, 148, 0)},
              'ENSG00000054392': {'microglia': (15127, 152, 0)},
              'ENSG00000054523': {'microglia': (9612, 212, 2666)},
              'ENSG00000055070': {'microglia': (6533, 122, 1396)},
              'ENSG00000055732': {'microglia': (5381, 102, 978)},
              'ENSG00000057252': {'microglia': (6950, 119, 216)},
              'ENSG00000057468': {'microglia': (7605, 82, 1605)},
              'ENSG00000057757': {'microglia': (5188, 186, 1391)},
              'ENSG00000058085': {'microglia': (6562, 115, 266)},
              'ENSG00000058453': {'microglia': (8847, 355, 2248)},
              'ENSG00000058668': {'microglia': (8354, 121, 0)},
              'ENSG00000058673': {'microglia': (6693, 136, 0)},
              'ENSG00000058799': {'microglia': (5941, 145, 1300)},
              'ENSG00000058804': {'microglia': (6909, 140, 1314)},
              'ENSG00000059588': {'microglia': (7810, 213, 0)},
              'ENSG00000060642': {'microglia': (4715, 230, 1245)},
              'ENSG00000060656': {'microglia': (7435, 121, 1610)},
              'ENSG00000060688': {'microglia': (6008, 64, 1442)},
              'ENSG00000060718': {'microglia': (12224, 77, 1870)},
              'ENSG00000064703': {'microglia': (5389, 197, 1165)},
              'ENSG00000064886': {'microglia': (6374, 180, 1179)},
              'ENSG00000065135': {'microglia': (5739, 325, 2105)},
              'ENSG00000065183': {'microglia': (5541, 113, 1026)},
              'ENSG00000065243': {'microglia': (8490, 110, 1680)},
              'ENSG00000065526': {'microglia': (7773, 336, 1838)},
              'ENSG00000065600': {'microglia': (5836, 147, 0)},
              'ENSG00000065978': {'microglia': (5286, 142, 1660)},
              'ENSG00000066027': {'microglia': (6384, 138, 0)},
              'ENSG00000066056': {'microglia': (5508, 247, 1796)},
              'ENSG00000066135': {'microglia': (6785, 205, 2111)},
              'ENSG00000066136': {'microglia': (7063, 88, 1695)},
              'ENSG00000066185': {'microglia': (5602, 85, 1591)},
              'ENSG00000066279': {'microglia': (6337, 237, 0)},
              'ENSG00000066294': {'microglia': (6565, 98, 186)},
              'ENSG00000066322': {'microglia': (4994, 320, 1932)},
              'ENSG00000066557': {'microglia': (5719, 56, 1513)},
              'ENSG00000067208': {'microglia': (11346, 151, 1860)},
              'ENSG00000067334': {'microglia': (5300, 133, 781)},
              'ENSG00000067533': {'microglia': (6621, 88, 0)},
              'ENSG00000067606': {'microglia': (12452, 200, 4984)},
              'ENSG00000067704': {'microglia': (5874, 101, 0)}}})

## Alpha Missense

In [15]:
alpha_miss = '/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations_hg38/merged_annotations_ADSP_v2/alphamissense/AlphaMissense_hg38.tsv.gz'
alpha = pd.read_csv(alpha_miss, sep = "\t", skiprows=3)
print(alpha.head)

<bound method NDFrame.head of          #CHROM       POS REF ALT genome uniprot_id             transcript_id  \
0          chr1     69094   G   T   hg38     Q8NH21         ENST00000335137.4
1          chr1     69094   G   C   hg38     Q8NH21         ENST00000335137.4
2          chr1     69094   G   A   hg38     Q8NH21         ENST00000335137.4
3          chr1     69095   T   C   hg38     Q8NH21         ENST00000335137.4
4          chr1     69095   T   A   hg38     Q8NH21         ENST00000335137.4
...         ...       ...  ..  ..    ...        ...                       ...
71697551   chrY  57196925   T   G   hg38     Q01113  ENST00000244174.10_PAR_Y
71697552   chrY  57196925   T   C   hg38     Q01113  ENST00000244174.10_PAR_Y
71697553   chrY  57196925   T   A   hg38     Q01113  ENST00000244174.10_PAR_Y
71697554   chrY  57196926   C   G   hg38     Q01113  ENST00000244174.10_PAR_Y
71697555   chrY  57196926   C   A   hg38     Q01113  ENST00000244174.10_PAR_Y

         protein_variant  am_pathogenicity           am_class
0                    V2L            0.2937      likely_benign
1                    V2L            0.2937      likely_benign
2                    V2M            0.3296      likely_benign
3                    V2A            0.2609      likely_benign
4                    V2E            0.2922      likely_benign
...                  ...               ...                ...
71697551           F521C            0.1903      likely_benign
71697552           F521S            0.2045      likely_benign
71697553           F521Y            0.1440      likely_benign
71697554           F521L            0.5879  likely_pathogenic
71697555           F521L            0.5879  likely_pathogenic

[71697556 rows x 10 columns]>

In [16]:
alpha['#CHROM']

0           chr1
1           chr1
2           chr1
3           chr1
4           chr1
            ...
71697551    chrY
71697552    chrY
71697553    chrY
71697554    chrY
71697555    chrY
Name: #CHROM, Length: 71697556, dtype: object

## LOF + Missense

In [3]:
CHRO_NB = 21
path = f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/36K_QC/VEP_annotations/chr{CHRO_NB}_LOF.txt"
lof = pd.read_csv(path, sep = "\t", skiprows=4).reset_index().drop_duplicates("level_1")
path = f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/36K_QC/VEP_annotations/chr{CHRO_NB}_missense.txt"
missense = pd.read_csv(path, sep = "\t", header = None).drop_duplicates(1)
# variants = np.array(data['pos'].astype(int))
# data['lof'] = np.where(pd.DataFrame(variants).isin(list(lof['level_1'].str.split(":").str[1].astype(int))), 1, 0)
# data['missense'] = np.where(pd.DataFrame(variants).isin(list(missense[1].str.split(":").str[1].astype(int))), 1, 0)

In [8]:
lof

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,level_10,level_11,level_12,"## VEP command-line: vep --assembly GRCh38 --canonical --dir_plugins [PATH]/loftee --format vcf --input_file [PATH]/ADSP.chr21.vcf.gz --output_file [PATH]/chr21.txt --plugin LoF,[PATH]/loftee,[PATH]/human_ancestor.fa.gz --variant_class"
0,21_14510308_A/T,21:14510308,T,ENSG00000155307,ENST00000285670,Transcript,splice_donor_variant,-,-,-,-,-,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;LoF=HC...
4,rs1357059260,21:14512443,T,ENSG00000155307,ENST00000285670,Transcript,splice_donor_variant,-,-,-,-,-,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;LoF=HC...
8,rs757290848,21:14521221,A,ENSG00000155307,ENST00000285670,Transcript,"stop_gained,splice_region_variant",437,262,88,R/*,Cga/Tga,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;LoF=HC...
11,rs190362907,21:14582137,T,ENSG00000155307,ENST00000285670,Transcript,"stop_gained,splice_region_variant",435,260,87,W/*,tGg/tAg,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;LoF=HC...
13,rs985716497,21:14582202,T,ENSG00000155307,ENST00000285670,Transcript,stop_gained,370,195,65,C/*,tgC/tgA,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;LoF=HC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2027,rs777561357,21:46563919,G,ENSG00000160305,ENST00000400274,Transcript,stop_gained,4372,4139,1380,S/*,tCa/tGa,-,IMPACT=HIGH;STRAND=1;VARIANT_CLASS=SNV;LoF=HC;...
2030,rs766516434,21:46599504,T,ENSG00000160307,ENST00000291700,Transcript,splice_acceptor_variant,-,-,-,-,-,-,IMPACT=HIGH;STRAND=-1;VARIANT_CLASS=SNV;CANONI...
2033,rs1286619153,21:46644453,T,ENSG00000160310,ENST00000291705,Transcript,stop_gained,470,292,98,Q/*,Cag/Tag,-,IMPACT=HIGH;STRAND=1;VARIANT_CLASS=SNV;LoF=HC;...
2043,rs1260399381,21:46652872,T,ENSG00000160310,ENST00000455177,Transcript,stop_gained,501,502,168,E/*,Gag/Tag,-,"IMPACT=HIGH;STRAND=1;FLAGS=cds_start_NF,cds_en..."
2044,21_46661798_A/C,21:46661798,C,ENSG00000160310,ENST00000355680,Transcript,splice_acceptor_variant,-,-,-,-,-,-,IMPACT=HIGH;STRAND=1;VARIANT_CLASS=SNV;CANONIC...

In [9]:
missense

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,rs1982880189,21:14373621,C,ENSG00000155304,ENST00000285667,Transcript,missense_variant,1439,1412,471,N/S,aAc/aGc,-,IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;CA...
1,rs547143733,21:14373671,A,ENSG00000155304,ENST00000285667,Transcript,missense_variant,1389,1362,454,Q/H,caA/caT,-,IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;CA...
2,rs769171893,21:14373747,T,ENSG00000155304,ENST00000285667,Transcript,missense_variant,1313,1286,429,S/Y,tCt/tAt,-,IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;CA...
3,rs369475727,21:14373778,C,ENSG00000155304,ENST00000285667,Transcript,missense_variant,1282,1255,419,Q/E,Caa/Gaa,-,IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;CA...
4,rs200646454,21:14373790,A,ENSG00000155304,ENST00000285667,Transcript,missense_variant,1270,1243,415,R/C,Cgt/Tgt,-,IMPACT=MODERATE;STRAND=-1;VARIANT_CLASS=SNV;CA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65675,rs140169346,21:46663507,A,ENSG00000160310,ENST00000355680,Transcript,missense_variant,1477,1222,408,A/T,Gct/Act,-,IMPACT=MODERATE;STRAND=1;VARIANT_CLASS=SNV;CAN...
65680,rs1445304119,21:46663544,T,ENSG00000160310,ENST00000355680,Transcript,missense_variant,1514,1259,420,T/I,aCa/aTa,-,IMPACT=MODERATE;STRAND=1;VARIANT_CLASS=SNV;CAN...
65684,rs369158228,21:46664358,T,ENSG00000160310,ENST00000458387,Transcript,missense_variant,1115,890,297,A/V,gCa/gTa,-,IMPACT=MODERATE;STRAND=1;VARIANT_CLASS=SNV
65685,rs765598184,21:46664360,C,ENSG00000160310,ENST00000458387,Transcript,missense_variant,1117,892,298,Y/H,Tat/Cat,-,IMPACT=MODERATE;STRAND=1;VARIANT_CLASS=SNV
65686,rs7283432,21:46664370,A,ENSG00000160310,ENST00000458387,Transcript,missense_variant,1127,902,301,G/E,gGg/gAg,-,IMPACT=MODERATE;STRAND=1;VARIANT_CLASS=SNV

In [2]:
CHRO_NB = 21
abc = pd.DataFrame()
for cell in ['microglia','neuron','oligodendrocyte','astrocyte']:
    path_hg38new = f"/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/brain_all/glass_lab_fastq/processed_files/ABC_data/ABC_results_{cell}_v2/{cell}/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
    cell_df= pd.read_csv(path_hg38new, sep = "\t")
    cell_df = cell_df[cell_df['ABC.Score']>=0.02]
    cell_df = cell_df[cell_df['chr']==f'chr{CHRO_NB}']
    cell_df['Cell'] = cell
    abc = pd.concat((abc, cell_df))
print(abc.head)

<bound method NDFrame.head of            chr     start       end                                name  \
5256379  chr21  14215841  14216761    promoter|chr21:14215841-14216761
5256390  chr21  14216965  14217465       genic|chr21:14216965-14217465
5256478  chr21  14272654  14274278  intergenic|chr21:14272654-14274278
5256621  chr21  14382938  14383539    promoter|chr21:14382938-14383539
5256622  chr21  14382938  14383539    promoter|chr21:14382938-14383539
...        ...       ...       ...                                 ...
4974806  chr21  46634923  46636405    promoter|chr21:46634923-46636405
4974807  chr21  46634923  46636405    promoter|chr21:46634923-46636405
4974808  chr21  46634923  46636405    promoter|chr21:46634923-46636405
4974809  chr21  46634923  46636405    promoter|chr21:46634923-46636405
4974810  chr21  46634923  46636405    promoter|chr21:46634923-46636405

              class  activity_base  activity_base_enh  \
5256379    promoter       2.952496           2.952496
5256390       genic       0.727641           0.727641
5256478  intergenic       9.829609           9.829609
5256621    promoter      16.934850          16.934850
5256622    promoter      16.934850          16.934850
...             ...            ...                ...
4974806    promoter      16.883359          16.883359
4974807    promoter      16.883359          16.883359
4974808    promoter      16.883359          16.883359
4974809    promoter      16.883359          16.883359
4974810    promoter      16.883359          16.883359

         activity_base_squared_enh  normalized_atac_enh  \
5256379                   8.717233             7.088440
5256390                   0.529461             1.293102
5256478                  96.621213            14.689413
5256621                 286.789145            59.490228
5256622                 286.789145            59.490228
...                            ...                  ...
4974806                 285.047811            12.420647
4974807                 285.047811            12.420647
4974808                 285.047811            12.420647
4974809                 285.047811            12.420647
4974810                 285.047811            12.420647

         normalized_h3k27ac_enh  ... hic_contact_pl_scaled  hic_pseudocount  \
5256379                1.229782  ...              0.181916         0.063014
5256390                0.409450  ...              0.181916         0.063014
5256478                6.577608  ...              0.007770         0.005181
5256621                4.820777  ...              0.006055         0.001732
5256622                4.820777  ...              0.159170         0.063014
...                         ...  ...                   ...              ...
4974806               22.949514  ...              0.012975         0.000914
4974807               22.949514  ...              0.012974         0.000915
4974808               22.949514  ...              0.023311         0.001636
4974809               22.949514  ...              0.022532         0.009875
4974810               22.949514  ...              0.265121         0.063014

         hic_contact_pl_scaled_adj  ABC.Score.Numerator  ABC.Score  \
5256379                   0.244930             0.723156   1.000000
5256390                   0.244930             0.178221   0.053074
5256478                   0.012950             0.127298   0.037909
5256621                   0.007787             0.131870   0.039271
5256622                   0.222184             3.762652   1.000000
...                            ...                  ...        ...
4974806                   0.013890             0.234508   0.039054
4974807                   0.013889             0.234495   0.039051
4974808                   0.024946             0.421178   0.073252
4974809                   0.032407             0.547135   0.082728
4974810                   0.328135             5.540020   1.000000

        powerlaw.Score.Numerator  powerlaw.Score   CellType  \
5256379                 0.186050        1.000000  microglia
5256390                 0.045852        0.063479  microglia
5256478                 0.050923        0.070499  microglia
5256621                 0.029332        0.040608  microglia
5256622                 1.067139        1.000000  microglia
...                          ...             ...        ...
4974806                 0.015439        0.014467  astrocyte
4974807                 0.015450        0.014483  astrocyte
4974808                 0.027615        0.027940  astrocyte
4974809                 0.166723        0.120357  astrocyte
4974810                 1.063895        1.000000  astrocyte

         hic_contact_squared       Cell
5256379             0.008625  microglia
5256390             0.008625  microglia
5256478             0.000007  microglia
5256621             0.000003  microglia
5256622             0.006603  microglia
...                      ...        ...
4974806             0.000012  astrocyte
4974807             0.000012  astrocyte
4974808             0.000047  astrocyte
4974809             0.000076  astrocyte
4974810             0.018318  astrocyte

[3217 rows x 33 columns]>

In [3]:
abc.columns

Index(['chr', 'start', 'end', 'name', 'class', 'activity_base',
       'activity_base_enh', 'activity_base_squared_enh', 'normalized_atac_enh',
       'normalized_h3k27ac_enh', 'TargetGene', 'TargetGeneTSS',
       'TargetGeneExpression', 'TargetGenePromoterActivityQuantile',
       'TargetGeneIsExpressed', 'TargetGeneEnsembl_ID', 'normalized_atac_prom',
       'normalized_h3k27ac_prom', 'distance', 'isSelfPromoter',
       'powerlaw_contact', 'powerlaw_contact_reference', 'hic_contact',
       'hic_contact_pl_scaled', 'hic_pseudocount', 'hic_contact_pl_scaled_adj',
       'ABC.Score.Numerator', 'ABC.Score', 'powerlaw.Score.Numerator',
       'powerlaw.Score', 'CellType', 'hic_contact_squared', 'Cell'],
      dtype='object')

In [5]:
abc['TargetGeneEnsembl_ID']

5256379    ENSG00000185272
5256390    ENSG00000185272
5256478    ENSG00000185272
5256621    ENSG00000185272
5256622    ENSG00000155304
                ...
4974806    ENSG00000160298
4974807    ENSG00000160299
4974808    ENSG00000160305
4974809    ENSG00000160307
4974810    ENSG00000160310
Name: TargetGeneEnsembl_ID, Length: 3217, dtype: object

In [33]:
import pandas as pd
import os

genotype_dir = "/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/genotypes"
annotation_dir = "/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/annotations"


ann_df = pd.read_csv(os.path.join(annotation_dir, "chr22", "ENSG00000100294_annotations.tsv.gz"), sep = "\t")
ann_df.head()



geno_df = pd.read_csv(os.path.join(genotype_dir, "chr22", "ENSG00000100294_genotypes.tsv.gz"), sep = "\t", index_col = "IID")
geno_df.head()

,22:43033017_C_A,22:43033027_T_C,22:43033220_T_C,22:43033334_C_T,22:43033930_G_A,22:43034113_A_G,22:43034131_T_C,22:43034173_T_G,22:43034335_A_G,22:43035440_A_G,...,22:43241699_C_G,22:43241758_T_C,22:43241863_T_C,22:43241973_A_T,22:43242477_T_C,22:43242646_G_T,22:43242729_A_G,22:43242811_C_G,22:43243132_G_A,22:43243260_C_G
IID,,,,,,,,,,,,,,,,,,,,,
CASE-NEUAE810KF7-9607-T,0.00142,0.0,0.002455,0.002457,0.002194,0.0,0.0,0.001291,0.0,0.001162,...,0.0,0,0,0,1,1.0,1,0.0,0,0
CASE-NEUAK233YVY-9803-T,0.00142,0.0,0.002455,0.002457,0.002194,0.0,0.0,0.001291,0.0,0.001162,...,0.0,0,0,0,0,0.0,0,0.0,0,0
CASE-NEUAL614GYB-8618-T,0.00142,0.0,0.002455,0.002457,0.002194,0.0,0.0,0.001291,0.0,0.001162,...,0.0,0,0,0,0,0.0,0,0.0,0,0
CASE-NEUAN180JPP-10533-T,0.00142,0.0,0.002455,0.002457,0.002194,0.0,0.0,0.001291,0.0,0.001162,...,0.0,0,0,0,0,0.0,0,0.0,0,0
CASE-NEUAP460GUX-10708-T,0.00142,0.0,0.002455,0.002457,0.002194,0.0,0.0,0.001291,0.0,0.001162,...,0.0,0,0,0,0,0.0,0,0.0,0,0

In [34]:
ann_df.head()

,variant_id,chr,pos,MAP20,phyloP17way_primate,phyloP30way_mammalian,phastCons17way_primate_rankscore,phastCons30way_mammalian,GERP_RS,bStatistic,...,log_counts_diff_chrombpnet_astrocyte,log_counts_diff_chrombpnet_neuron,log_counts_diff_chrombpnet_oligodendrocyte,alphamissense,splice,ABC_microglia,ABC_neuron,ABC_oligodendrocyte,ABC_astrocyte,dist_to_TSS
0,0,22.0,43033017.0,0.037500,0.276,0.319,0.48053,0.060,0.113,735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.042879
1,1,22.0,43033027.0,0.000000,0.225,0.260,0.49222,0.057,0.113,735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.042839
2,2,22.0,43033220.0,0.787500,-0.828,-0.727,0.08282,0.001,-0.226,735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.042079
3,3,22.0,43033334.0,0.000000,0.249,0.275,0.71733,0.205,0.113,735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.041630
4,4,22.0,43033930.0,0.616667,-0.096,0.716,0.49222,0.152,-1.650,735.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.039271

In [30]:
from collections import defaultdict
import os
import pandas as pd
import re

## add index column back to annotation matrices
ref_dir = "/gpfs/commons/groups/knowles_lab/vmazeeva/BigBrain/Processed/reference"
for chrom in range(1,23):
    if chrom == 21: continue
    for file in os.listdir(os.path.join(annotation_dir, f"chr{chrom}")):
        if not file.endswith("_annotations.tsv.gz"):
            continue

        gene = re.sub(r"_annotations\.tsv\.gz$", "", file)
        
        anno_df = pd.read_csv(os.path.join(annotation_dir, f"chr{chrom}", file), sep = "\t")
        geno_df = pd.read_csv(os.path.join(genotype_dir, f"chr{chrom}", f"{gene}_genotypes.tsv.gz"), sep = "\t", index_col = "IID")
        variant_ids = geno_df.columns
        pos_to_alleles = dict()
        for variant_id in variant_ids:
            chr, pos_alleles = variant_id.split(":") 
            pos, counted, other = pos_alleles.split("_")
            pos_to_alleles[pos] = (counted, other)

        ref_table = pd.read_csv(os.path.join(ref_dir, f"chr{chrom}_ref.tsv.gz"), sep = "\t",
                    compression="gzip",
                    names=["chr", "pos", "ref"],
                    dtype={"chr": str, "pos": int, "ref": str})
        anno_df2 = pd.merge(anno_df, ref_table, on = ['pos'], how = 'left')
        anno_varids = []
        for _, row in anno_df2.iterrows():
            pos = row['pos']
            ref = row['ref']
            alt = ''
            counted_other = pos_to_alleles[str(int(pos))]
            if ref == counted_other[0]:
                alt = counted_other[1]
            else:
                alt = counted_other[0]
            anno_varids.append(f"{int(row['chr_x'])}:{row['pos']}_{ref}_{alt}")
        assert len(anno_varids) == len(anno_df), f"Mismatch: {len(anno_varids)} genotype variants vs {len(anno_df)} annotations"
        assert len(geno_df.columns) == len(anno_varids), f"Mismatch: {len(geno_df.columns)} genotype variants vs {len(anno_varids)} annotations"
        anno_df2['variant_id'] = anno_varids
        anno_df2.drop(columns=['ref', 'chr_y'], inplace=True)
        anno_df2.rename(columns={'chr_x': 'chr'}, inplace=True)
        anno_df2.set_index('variant_id', inplace=True)
        anno_df.index.name = 'variant_id'
        assert anno_df.values.shape == anno_df2.values.shape, f"Mismatch: {anno_df.values.shape} annotation matrix vs {anno_df2.values.shape} annotation matrix"
        assert (anno_df.values == anno_df2.values).all(), "Annotation matrices do not match"
        anno_df.to_csv(os.path.join(annotation_dir, f"chr{chrom}", file), sep = "\t", index=True, compression="gzip")

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [27]:
anno_df2.head()

,chr,pos,MAP20,phyloP17way_primate,phyloP30way_mammalian,phastCons17way_primate_rankscore,phastCons30way_mammalian,GERP_RS,bStatistic,integrated_fitCons_score,...,log_counts_diff_chrombpnet_astrocyte,log_counts_diff_chrombpnet_neuron,log_counts_diff_chrombpnet_oligodendrocyte,alphamissense,splice,ABC_microglia,ABC_neuron,ABC_oligodendrocyte,ABC_astrocyte,dist_to_TSS
variant_id,,,,,,,,,,,,,,,,,,,,,
1:179740033.0_A_T,1.0,179740033.0,0.90,-0.415,0.431,0.14158,0.007,-0.352,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.139155
1:179740457.0_G_A,1.0,179740457.0,1.00,-0.487,0.009,0.18454,0.003,0.462,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137816
1:179740573.0_C_G,1.0,179740573.0,1.00,-0.390,-0.048,0.77633,0.000,-2.040,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137449
1:179740627.0_C_G,1.0,179740627.0,1.00,-0.649,-0.533,0.39275,0.004,-0.708,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137278
1:179740695.0_G_A,1.0,179740695.0,0.95,0.498,0.003,0.71945,0.010,-0.249,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137063

In [20]:
geno_df.head()

,1:179740033_T_A,1:179740457_G_A,1:179740573_G_C,1:179740627_G_C,1:179740695_A_G,1:179740726_T_G,1:179740913_G_A,1:179740958_C_T,1:179740990_T_C,1:179741218_T_C,...,1:179975486_T_G,1:179975711_C_G,1:179975766_G_A,1:179975793_A_C,1:179976102_A_G,1:179976255_G_A,1:179976886_T_G,1:179977141_T_G,1:179977171_C_G,1:179977711_G_A
IID,,,,,,,,,,,,,,,,,,,,,
CASE-NEUAE810KF7-9607-T,0.0,2.0,0,0.0,0,0,0,0.0,0.000903,0,...,0.0,0.0,1,1.0,0.0,1.0,0,0,0,0.0
CASE-NEUAK233YVY-9803-T,0.0,1.0,0,0.0,0,0,0,0.0,0.000903,0,...,0.0,0.0,0,0.0,0.0,2.0,0,0,0,0.0
CASE-NEUAL614GYB-8618-T,1.0,0.0,0,1.0,0,0,0,0.0,0.000903,0,...,0.0,0.0,1,1.0,0.0,0.0,0,0,0,0.0
CASE-NEUAN180JPP-10533-T,1.0,1.0,0,1.0,0,0,0,0.0,0.000903,0,...,0.0,0.0,0,1.0,0.0,0.0,0,1,0,0.0
CASE-NEUAP460GUX-10708-T,1.0,1.0,0,1.0,0,0,0,0.0,0.000903,0,...,0.0,0.0,1,1.0,0.0,0.0,0,0,0,0.0

In [19]:
anno_df.head()

,chr,pos,MAP20,phyloP17way_primate,phyloP30way_mammalian,phastCons17way_primate_rankscore,phastCons30way_mammalian,GERP_RS,bStatistic,integrated_fitCons_score,...,log_counts_diff_chrombpnet_astrocyte,log_counts_diff_chrombpnet_neuron,log_counts_diff_chrombpnet_oligodendrocyte,alphamissense,splice,ABC_microglia,ABC_neuron,ABC_oligodendrocyte,ABC_astrocyte,dist_to_TSS
0,1.0,179740033.0,0.90,-0.415,0.431,0.14158,0.007,-0.352,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.139155
1,1.0,179740457.0,1.00,-0.487,0.009,0.18454,0.003,0.462,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137816
2,1.0,179740573.0,1.00,-0.390,-0.048,0.77633,0.000,-2.040,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137449
3,1.0,179740627.0,1.00,-0.649,-0.533,0.39275,0.004,-0.708,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137278
4,1.0,179740695.0,0.95,0.498,0.003,0.71945,0.010,-0.249,764.0,0.06567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.137063

In [10]:
pos_to_alleles

defaultdict(list,
            {'179740033': ('T', 'A'),
             '179740457': ('G', 'A'),
             '179740573': ('G', 'C'),
             '179740627': ('G', 'C'),
             '179740695': ('A', 'G'),
             '179740726': ('T', 'G'),
             '179740913': ('G', 'A'),
             '179740958': ('C', 'T'),
             '179740990': ('T', 'C'),
             '179741218': ('T', 'C'),
             '179741285': ('C', 'T'),
             '179741524': ('T', 'C'),
             '179741531': ('G', 'A'),
             '179741933': ('C', 'T'),
             '179742503': ('T', 'A'),
             '179742514': ('G', 'T'),
             '179742690': ('C', 'A'),
             '179742751': ('A', 'C'),
             '179742755': ('A', 'C'),
             '179743039': ('T', 'C'),
             '179743088': ('C', 'A'),
             '179743176': ('A', 'C'),
             '179743185': ('T', 'G'),
             '179743263': ('A', 'C'),
             '179743304': ('T', 'C'),
             '179743320': ('A', 'G'),
             '179743345': ('T', 'G'),
             '179743373': ('G', 'C'),
             '179743414': ('A', 'C'),
             '179743579': ('T', 'C'),
             '179743780': ('T', 'C'),
             '179743846': ('T', 'C'),
             '179743860': ('G', 'C'),
             '179744178': ('A', 'G'),
             '179744293': ('T', 'C'),
             '179744324': ('C', 'G'),
             '179744325': ('G', 'A'),
             '179744400': ('C', 'G'),
             '179744504': ('A', 'G'),
             '179744620': ('A', 'G'),
             '179744705': ('A', 'C'),
             '179744869': ('A', 'G'),
             '179744889': ('T', 'C'),
             '179744896': ('T', 'C'),
             '179744994': ('G', 'A'),
             '179745052': ('T', 'G'),
             '179745246': ('G', 'T'),
             '179745503': ('C', 'G'),
             '179745716': ('C', 'T'),
             '179745921': ('A', 'G'),
             '179746159': ('A', 'T'),
             '179746166': ('A', 'G'),
             '179746221': ('C', 'T'),
             '179746264': ('G', 'A'),
             '179746435': ('A', 'G'),
             '179746550': ('A', 'G'),
             '179746730': ('A', 'C'),
             '179747242': ('T', 'G'),
             '179747312': ('G', 'C'),
             '179747356': ('C', 'T'),
             '179747372': ('C', 'T'),
             '179747446': ('G', 'C'),
             '179747736': ('G', 'T'),
             '179747790': ('G', 'T'),
             '179747821': ('C', 'A'),
             '179747924': ('A', 'G'),
             '179748155': ('C', 'G'),
             '179748289': ('G', 'T'),
             '179748636': ('A', 'G'),
             '179748717': ('T', 'C'),
             '179748763': ('C', 'G'),
             '179749006': ('G', 'A'),
             '179749268': ('C', 'T'),
             '179749580': ('A', 'G'),
             '179749888': ('C', 'T'),
             '179749989': ('G', 'A'),
             '179750181': ('C', 'T'),
             '179750230': ('C', 'T'),
             '179750304': ('G', 'A'),
             '179750362': ('G', 'A'),
             '179750431': ('T', 'A'),
             '179751055': ('A', 'C'),
             '179751528': ('T', 'G'),
             '179751535': ('A', 'G'),
             '179751627': ('A', 'G'),
             '179752145': ('T', 'C'),
             '179752234': ('G', 'T'),
             '179752236': ('T', 'G'),
             '179752462': ('G', 'A'),
             '179752636': ('T', 'G'),
             '179752773': ('G', 'A'),
             '179753085': ('G', 'C'),
             '179753362': ('C', 'G'),
             '179753614': ('A', 'G'),
             '179753615': ('G', 'T'),
             '179753629': ('T', 'G'),
             '179753692': ('G', 'T'),
             '179753920': ('A', 'G'),
             '179754062': ('T', 'C'),
             '179754624': ('A', 'G'),
             '179754715': ('T', 'C'),
             '179754736': ('T', 'C'),
             '179754811': ('C', 'G'),
             '179755216': ('C', 'G'),
             '179755295': ('C', 'T'),
             '179755457': ('C', 'T'),
             '179755524': ('C', 'G'),
             '179755657': ('G', 'A'),
             '179755690': ('G', 'A'),
             '179755901': ('C', 'T'),
             '179755921': ('T', 'A'),
             '179756134': ('G', 'C'),
             '179756344': ('C', 'T'),
             '179756418': ('C', 'T'),
             '179756479': ('C', 'T'),
             '179756562': ('A', 'T'),
             '179756615': ('G', 'A'),
             '179756778': ('C', 'A'),
             '179756864': ('C', 'T'),
             '179756941': ('A', 'G'),
             '179756952': ('A', 'G'),
             '179757169': ('G', 'A'),
             '179757297': ('G', 'A'),
             '179757606': ('A', 'G'),
             '179757965': ('T', 'C'),
             '179758018': ('A', 'G'),
             '179758167': ('T', 'G'),
             '179758321': ('C', 'G'),
             '179758535': ('T', 'A'),
             '179758617': ('T', 'C'),
             '179758665': ('A', 'G'),
             '179758809': ('G', 'T'),
             '179759011': ('C', 'T'),
             '179759061': ('T', 'C'),
             '179759105': ('C', 'T'),
             '179759206': ('A', 'G'),
             '179759466': ('G', 'T'),
             '179759603': ('A', 'G'),
             '179759629': ('T', 'G'),
             '179759991': ('A', 'G'),
             '179760041': ('G', 'A'),
             '179760122': ('T', 'A'),
             '179760419': ('A', 'G'),
             '179760508': ('A', 'G'),
             '179760868': ('C', 'T'),
             '179760886': ('T', 'C'),
             '179760946': ('T', 'C'),
             '179760967': ('T', 'C'),
             '179761037': ('T', 'G'),
             '179761131': ('A', 'T'),
             '179761288': ('G', 'A'),
             '179761329': ('A', 'G'),
             '179761410': ('G', 'A'),
             '179762024': ('G', 'A'),
             '179762298': ('C', 'T'),
             '179762318': ('G', 'A'),
             '179762415': ('A', 'G'),
             '179762503': ('T', 'C'),
             '179762545': ('C', 'A'),
             '179762813': ('T', 'G'),
             '179762965': ('G', 'A'),
             '179763007': ('A', 'G'),
             '179763365': ('G', 'A'),
             '179763488': ('A', 'G'),
             '179763572': ('T', 'C'),
             '179763835': ('T', 'C'),
             '179764035': ('C', 'T'),
             '179764058': ('G', 'A'),
             '179764320': ('T', 'C'),
             '179764540': ('C', 'T'),
             '179764543': ('A', 'G'),
             '179764609': ('G', 'C'),
             '179764621': ('A', 'G'),
             '179764663': ('C', 'T'),
             '179764676': ('A', 'G'),
             '179764774': ('G', 'C'),
             '179764868': ('A', 'G'),
             '179765064': ('G', 'A'),
             '179765104': ('A', 'G'),
             '179765160': ('T', 'G'),
             '179765286': ('G', 'A'),
             '179766124': ('G', 'A'),
             '179766154': ('G', 'A'),
             '179766184': ('T', 'C'),
             '179766252': ('C', 'A'),
             '179766523': ('T', 'C'),
             '179766553': ('A', 'G'),
             '179767140': ('T', 'C'),
             '179767184': ('C', 'T'),
             '179767313': ('G', 'A'),
             '179767435': ('C', 'T'),
             '179767486': ('G', 'C'),
             '179767570': ('A', 'G'),
             '179767664': ('T', 'C'),
             '179767747': ('T', 'C'),
             '179767970': ('G', 'A'),
             '179768372': ('C', 'A'),
             '179768955': ('T', 'C'),
             '179769163': ('G', 'T'),
             '179769310': ('C', 'T'),
             '179769405': ('C', 'G'),
             '179769465': ('T', 'A'),
             '179769591': ('C', 'A'),
             '179769665': ('G', 'A'),
             '179769675': ('A', 'G'),
             '179769728': ('A', 'G'),
             '179769769': ('G', 'A'),
             '179770269': ('G', 'A'),
             '179770613': ('T', 'C'),
             '179770894': ('A', 'G'),
             '179771078': ('T', 'A'),
             '179771297': ('C', 'T'),
             '179771382': ('T', 'C'),
             '179771587': ('A', 'G'),
             '179772290': ('T', 'C'),
             '179772400': ('T', 'G'),
             '179772404': ('C', 'A'),
             '179773357': ('A', 'G'),
             '179773529': ('G', 'A'),
             '179773684': ('C', 'A'),
             '179774059': ('C', 'T'),
             '179774349': ('A', 'G'),
             '179774566': ('A', 'G'),
             '179774665': ('C', 'G'),
             '179774741': ('T', 'C'),
             '179775023': ('T', 'C'),
             '179775097': ('T', 'G'),
             '179775206': ('T', 'C'),
             '179775320': ('T', 'C'),
             '179775791': ('T', 'C'),
             '179775875': ('A', 'G'),
             '179775878': ('A', 'G'),
             '179776028': ('A', 'G'),
             '179776110': ('G', 'C'),
             '179776146': ('A', 'G'),
             '179776262': ('T', 'C'),
             '179776631': ('C', 'T'),
             '179776697': ('G', 'A'),
             '179776912': ('G', 'A'),
             '179776955': ('A', 'G'),
             '179777174': ('C', 'T'),
             '179777200': ('T', 'C'),
             '179777852': ('A', 'G'),
             '179778071': ('G', 'A'),
             '179778244': ('A', 'C'),
             '179778250': ('A', 'G'),
             '179778265': ('G', 'C'),
             '179778326': ('G', 'A'),
             '179778768': ('A', 'G'),
             '179778905': ('A', 'C'),
             '179779089': ('C', 'T'),
             '179779129': ('C', 'T'),
             '179779326': ('G', 'C'),
             '179779379': ('T', 'C'),
             '179779607': ('A', 'G'),
             '179779804': ('A', 'G'),
             '179779863': ('T', 'C'),
             '179780653': ('C', 'T'),
             '179780792': ('C', 'T'),
             '179780863': ('A', 'G'),
             '179781145': ('G', 'A'),
             '179781307': ('T', 'A'),
             '179781375': ('T', 'C'),
             '179781512': ('A', 'G'),
             '179781578': ('C', 'G'),
             '179782089': ('T', 'C'),
             '179782122': ('C', 'A'),
             '179782156': ('G', 'C'),
             '179782180': ('C', 'T'),
             '179782374': ('G', 'A'),
             '179782444': ('G', 'A'),
             '179782563': ('C', 'T'),
             '179782684': ('A', 'G'),
             '179782842': ('C', 'T'),
             '179782843': ('T', 'C'),
             '179782921': ('A', 'C'),
             '179783316': ('A', 'G'),
             '179783959': ('A', 'G'),
             '179784012': ('G', 'A'),
             '179784051': ('A', 'G'),
             '179784158': ('C', 'T'),
             '179784542': ('C', 'T'),
             '179784921': ('G', 'T'),
             '179785184': ('G', 'C'),
             '179785544': ('C', 'T'),
             '179785655': ('T', 'C'),
             '179785941': ('T', 'C'),
             '179786165': ('G', 'A'),
             '179786448': ('T', 'C'),
             '179786804': ('T', 'C'),
             '179786944': ('A', 'T'),
             '179786975': ('T', 'C'),
             '179787061': ('T', 'C'),
             '179787171': ('G', 'C'),
             '179787388': ('C', 'T'),
             '179787504': ('T', 'C'),
             '179787529': ('T', 'C'),
             '179787573': ('T', 'C'),
             '179787646': ('G', 'C'),
             '179787672': ('A', 'G'),
             '179788435': ('T', 'A'),
             '179788641': ('A', 'G'),
             '179788703': ('C', 'T'),
             '179788720': ('G', 'T'),
             '179788757': ('A', 'G'),
             '179788909': ('G', 'C'),
             '179788946': ('A', 'G'),
             '179789308': ('G', 'A'),
             '179789391': ('G', 'A'),
             '179789595': ('T', 'C'),
             '179789765': ('T', 'A'),
             '179789832': ('G', 'A'),
             '179790012': ('A', 'G'),
             '179790036': ('G', 'A'),
             '179790535': ('T', 'C'),
             '179790653': ('A', 'T'),
             '179790663': ('C', 'A'),
             '179790681': ('G', 'C'),
             '179790752': ('A', 'G'),
             '179790952': ('T', 'C'),
             '179791160': ('A', 'G'),
             '179791165': ('G', 'A'),
             '179791193': ('T', 'C'),
             '179791467': ('T', 'G'),
             '179791555': ('A', 'G'),
             '179791648': ('T', 'C'),
             '179791649': ('A', 'G'),
             '179791717': ('T', 'C'),
             '179791807': ('G', 'A'),
             '179792466': ('G', 'A'),
             '179792734': ('G', 'A'),
             '179793135': ('G', 'T'),
             '179793404': ('C', 'G'),
             '179793499': ('T', 'C'),
             '179793588': ('T', 'C'),
             '179793882': ('G', 'T'),
             '179793900': ('T', 'C'),
             '179793914': ('G', 'A'),
             '179794006': ('G', 'C'),
             '179794134': ('T', 'C'),
             '179794476': ('G', 'A'),
             '179794731': ('G', 'T'),
             '179794734': ('A', 'G'),
             '179795202': ('G', 'A'),
             '179795365': ('C', 'G'),
             '179795478': ('G', 'A'),
             '179796230': ('T', 'C'),
             '179796533': ('A', 'G'),
             '179796643': ('C', 'A'),
             '179796693': ('C', 'G'),
             '179796951': ('T', 'C'),
             '179797037': ('G', 'T'),
             '179797097': ('A', 'C'),
             '179797527': ('T', 'C'),
             '179797900': ('T', 'C'),
             '179797924': ('G', 'A'),
             '179798086': ('T', 'C'),
             '179798143': ('T', 'A'),
             '179798299': ('G', 'A'),
             '179798302': ('T', 'C'),
             '179798434': ('C', 'T'),
             '179798477': ('C', 'T'),
             '179798834': ('G', 'C'),
             '179798861': ('C', 'T'),
             '179798924': ('A', 'G'),
             '179798937': ('T', 'C'),
             '179798982': ('G', 'C'),
             '179799049': ('T', 'G'),
             '179799329': ('C', 'T'),
             '179799465': ('T', 'C'),
             '179799646': ('T', 'C'),
             '179799931': ('G', 'T'),
             '179799989': ('C', 'T'),
             '179800131': ('G', 'A'),
             '179800352': ('T', 'C'),
             '179800388': ('T', 'C'),
             '179800484': ('C', 'T'),
             '179800621': ('A', 'G'),
             '179800635': ('C', 'G'),
             '179800720': ('C', 'T'),
             '179800726': ('C', 'A'),
             '179800739': ('A', 'G'),
             '179801121': ('T', 'C'),
             '179801145': ('G', 'A'),
             '179801598': ('A', 'G'),
             '179801722': ('G', 'A'),
             '179801826': ('C', 'A'),
             '179801837': ('T', 'C'),
             '179802059': ('G', 'T'),
             '179802065': ('T', 'G'),
             '179802146': ('G', 'A'),
             '179802227': ('G', 'A'),
             '179802315': ('G', 'A'),
             '179802508': ('G', 'A'),
             '179802735': ('T', 'C'),
             '179802856': ('T', 'C'),
             '179803025': ('C', 'T'),
             '179803118': ('C', 'A'),
             '179803126': ('T', 'C'),
             '179803127': ('A', 'G'),
             '179803389': ('T', 'C'),
             '179803434': ('G', 'A'),
             '179803435': ('G', 'A'),
             '179803490': ('G', 'C'),
             '179805030': ('C', 'T'),
             '179805192': ('C', 'G'),
             '179805217': ('C', 'G'),
             '179805240': ('A', 'G'),
             '179805458': ('T', 'C'),
             '179805998': ('C', 'A'),
             '179806149': ('G', 'C'),
             '179806188': ('G', 'A'),
             '179806440': ('A', 'G'),
             '179806452': ('T', 'C'),
             '179806532': ('A', 'G'),
             '179806547': ('C', 'T'),
             '179807365': ('A', 'G'),
             '179807402': ('C', 'G'),
             '179807485': ('T', 'G'),
             '179807501': ('T', 'C'),
             '179807506': ('A', 'C'),
             '179807515': ('T', 'C'),
             '179807640': ('A', 'G'),
             '179807706': ('G', 'A'),
             '179807751': ('C', 'G'),
             '179807968': ('C', 'G'),
             '179808303': ('A', 'G'),
             '179808847': ('T', 'A'),
             '179809024': ('C', 'T'),
             '179809297': ('C', 'T'),
             '179809367': ('T', 'C'),
             '179809719': ('A', 'G'),
             '179809752': ('A', 'G'),
             '179809906': ('C', 'T'),
             '179809918': ('T', 'C'),
             '179810398': ('C', 'G'),
             '179810432': ('T', 'C'),
             '179810654': ('T', 'C'),
             '179810663': ('G', 'A'),
             '179811499': ('T', 'C'),
             '179811700': ('A', 'C'),
             '179811802': ('A', 'G'),
             '179812166': ('C', 'T'),
             '179812379': ('G', 'C'),
             '179812395': ('T', 'C'),
             '179812600': ('C', 'G'),
             '179812697': ('C', 'G'),
             '179812956': ('T', 'C'),
             '179813017': ('A', 'C'),
             '179813089': ('A', 'G'),
             '179813418': ('A', 'G'),
             '179813910': ('T', 'C'),
             '179814032': ('T', 'G'),
             '179814152': ('G', 'C'),
             '179814343': ('C', 'T'),
             '179814657': ('A', 'C'),
             '179814871': ('A', 'G'),
             '179815496': ('A', 'C'),
             '179815549': ('G', 'A'),
             '179815554': ('C', 'T'),
             '179815804': ('T', 'C'),
             '179816369': ('T', 'C'),
             '179816602': ('A', 'G'),
             '179816697': ('C', 'G'),
             '179816702': ('T', 'C'),
             '179816739': ('A', 'G'),
             '179816774': ('A', 'G'),
             '179816870': ('T', 'C'),
             '179816911': ('C', 'G'),
             '179817062': ('G', 'A'),
             '179817121': ('A', 'G'),
             '179817250': ('C', 'T'),
             '179817736': ('G', 'A'),
             '179817805': ('T', 'A'),
             '179817871': ('C', 'T'),
             '179817892': ('G', 'A'),
             '179817919': ('C', 'T'),
             '179818031': ('T', 'C'),
             '179818137': ('G', 'A'),
             '179818390': ('A', 'G'),
             '179818504': ('G', 'C'),
             '179818627': ('T', 'C'),
             '179818801': ('T', 'C'),
             '179818833': ('T', 'C'),
             '179818847': ('T', 'C'),
             '179818956': ('G', 'C'),
             '179819001': ('G', 'A'),
             '179819198': ('T', 'C'),
             '179819699': ('C', 'T'),
             '179820399': ('C', 'T'),
             '179820421': ('C', 'A'),
             '179820757': ('A', 'G'),
             '179820811': ('T', 'G'),
             '179820829': ('C', 'G'),
             '179820854': ('C', 'A'),
             '179820925': ('T', 'C'),
             '179820975': ('T', 'G'),
             '179821431': ('T', 'C'),
             '179821598': ('T', 'C'),
             '179821635': ('C', 'A'),
             '179821710': ('A', 'G'),
             '179821848': ('A', 'G'),
             '179821852': ('T', 'C'),
             '179822199': ('C', 'T'),
             '179822227': ('A', 'G'),
             '179822400': ('A', 'G'),
             '179822735': ('C', 'T'),
             '179822774': ('C', 'T'),
             '179822935': ('T', 'C'),
             '179823841': ('G', 'A'),
             '179823914': ('A', 'G'),
             '179824096': ('T', 'G'),
             '179824147': ('G', 'T'),
             '179824202': ('A', 'G'),
             '179824372': ('G', 'T'),
             '179824376': ('G', 'C'),
             '179824564': ('C', 'G'),
             '179824587': ('T', 'C'),
             '179824757': ('T', 'C'),
             '179824877': ('A', 'G'),
             '179825024': ('C', 'T'),
             '179825234': ('C', 'T'),
             '179825282': ('T', 'G'),
             '179825283': ('C', 'G'),
             '179825467': ('G', 'A'),